name: FastAPI - CI

on:
  push:
    branches: [ "luis" ]
  pull_request:
    branches: [ "luis" ]

jobs:
  fastapi-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar prueba de la API
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl -X GET http://localhost:8000/docs || exit 1
